const SET_DATA = 'SET_DATE';
const APPLY_FILTER = 'APPLY_FILTER';
const FETCHING_DATA = 'FETCHING_DATA';
const FETCHED_DATA = 'FETCHED_DATA';

export {
  SET_DATA,
  APPLY_FILTER,
  FETCHING_DATA,
  FETCHED_DATA
};